#!/usr/bin/env node
// Third-party licences, from SPDX SBOMs.
//
//   node scripts/licences.mjs OUT.md SBOM.json [SBOM.json ...] [--check]
//
// Reads what syft writes — an SPDX document, or the {"<platform>": {"SPDX": …}} map that
// `docker buildx imagetools inspect --format '{{ json .SBOM }}'` prints for a published image —
// and writes one Markdown list: every package once, under its licence, most common first.
//
// --check also fails when one of the app's own dependencies (npm and PyPI packages) can only be
// used under a licence that does not fit an MIT project that may be offered commercially
// (DENIED below). That is how the non-commercial translation model slipped in, and a dependency
// could do the same; this catches it in review. Operating-system packages in an image are left
// out of the check: they are separate programs shipped alongside, and Debian publishes their
// source, which is what their GPL asks of a distributor.
// Licence expressions are read simply: an OR is fine when any side is allowed, an AND needs
// every part allowed, and nesting is flattened — near enough for what package metadata holds.

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const DENIED = [/^AGPL-/i, /^SSPL-/i, /^BUSL-/i, /^GPL-/i, /-NC(-|$)/i, /NonCommercial/i, /Commons-Clause/i];

/** The kinds of package the app itself depends on, and so the only ones --check judges. */
const CHECKED = new Set(["npm", "pypi"]);

/** This project's own packages, which appear in its lockfiles under its own name. */
const OURS = new Set(["voxinq", "voxinq-meeting"]);

const args = process.argv.slice(2);
const check = args.includes("--check");
const [out, ...inputs] = args.filter((a) => a !== "--check");
if (!out || inputs.length === 0) {
  console.error("usage: node scripts/licences.mjs OUT.md SBOM.json [SBOM.json ...] [--check]");
  process.exit(2);
}

/** Every SPDX document inside a value, however deeply the tool that wrote it wrapped them. */
function documents(value) {
  if (!value || typeof value !== "object") return [];
  if (typeof value.spdxVersion === "string") return [value];
  return Object.values(value).flatMap(documents);
}

function licenceOf(pkg) {
  const known = (v) => (typeof v === "string" && v !== "NOASSERTION" && v !== "NONE" ? v : null);
  return known(pkg.licenseConcluded) ?? known(pkg.licenseDeclared) ?? "unknown";
}

function purlOf(pkg) {
  return (pkg.externalRefs ?? []).find((r) => r.referenceType === "purl")?.referenceLocator ?? null;
}

function isDenied(expression) {
  return expression
    .replace(/[()]/g, " ")
    .split(/\s+AND\s+/i)
    .some((part) => part.split(/\s+OR\s+/i).every((alt) => DENIED.some((re) => re.test(alt.trim()))));
}

const packages = new Map();
for (const file of inputs) {
  for (const doc of documents(JSON.parse(readFileSync(file, "utf8")))) {
    for (const pkg of doc.packages ?? []) {
      const purl = purlOf(pkg);
      // Without a purl it is the scanned directory or image itself, not something inside it.
      // GitHub Actions run in CI and are not shipped.
      if (!purl || purl.startsWith("pkg:github/") || OURS.has(pkg.name)) continue;
      const kind = purl.slice(4, purl.indexOf("/"));
      const key = `${kind}:${pkg.name}@${pkg.versionInfo ?? ""}`;
      if (!packages.has(key)) {
        packages.set(key, { name: pkg.name, version: pkg.versionInfo ?? "", kind, licence: licenceOf(pkg) });
      }
    }
  }
}

const byLicence = new Map();
for (const p of packages.values()) {
  if (!byLicence.has(p.licence)) byLicence.set(p.licence, []);
  byLicence.get(p.licence).push(p);
}
const sections = [...byLicence.entries()].sort(
  ([a, x], [b, y]) => (a === "unknown") - (b === "unknown") || y.length - x.length || a.localeCompare(b),
);

const lines = [
  "# Third-party licences",
  "",
  `Every package found in ${inputs.map((f) => `\`${path.basename(f)}\``).join(", ")}, listed once under its licence.`,
  "Generated by `scripts/licences.mjs`; the SBOMs themselves are the complete record. See NOTICE.md for the",
  "models, and for what the GPL and other notices require.",
  "",
  `${packages.size} packages under ${byLicence.size} licences.`,
];
for (const [licence, list] of sections) {
  lines.push("", `## ${licence} (${list.length})`, "");
  for (const p of list.sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version))) {
    lines.push(`- ${p.name} ${p.version} (${p.kind})`);
  }
}
writeFileSync(out, lines.join("\n") + "\n");
console.log(`${out}: ${packages.size} packages, ${byLicence.size} licences`);

if (check) {
  const offending = [...packages.values()].filter(
    (p) => CHECKED.has(p.kind) && p.licence !== "unknown" && isDenied(p.licence),
  );
  if (offending.length > 0) {
    console.error("Licences that do not fit an MIT project offered commercially:");
    for (const p of offending) console.error(`  ${p.name} ${p.version} (${p.kind}): ${p.licence}`);
    process.exit(1);
  }
}
